# Generated by Django 6.0.1 on 2026-03-31 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0004_alter_subscriber_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='html_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='last_attempt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='message_body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='failed', max_length=10),
        ),
    ]
