# Generated by Django 6.0.1 on 2026-04-03 10:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0005_emaillog_html_body_emaillog_last_attempt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ['-subscribed_at']},
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='failed', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='Tee', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='posts', to='apicore.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Short summary shown on cards (150–300 chars recommended)', max_length=500),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_published', '-publish_date'], name='apicore_pos_is_publ_8152d2_idx'),
        ),
    ]
